kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes: 
- role: control-plane
  extraMounts:
  # please change this path to your real path.
  - hostPath: /home/tao/audit/audit 
    containerPath: /tmp/audit
- role: worker
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      audit-log-path: "/tmp/audit/audit.log"
      audit-policy-file: "/tmp/audit/policy.yaml"
    extraVolumes:
    - name: audit
      hostPath: /tmp/audit
      mountPath: /tmp/audit
